#!/usr/bin/env bash
RASI="$HOME/.config/hypr/rofi/styles/launcher.rasi"

rofi_cmd() {
	rofi -no-config \
        -no-lazy-grab \
        -show drun \
        -modi drun \
        -theme $RASI
}

rofi_cmd
