#!/usr/bin/env bash
style="rosemary"
dir="$HOME/.config/polybar/$style/rofi/"

rofi_cmd() {
	rofi -no-config \
        -no-lazy-grab \
        -show drun \
        -modi drun \
        -theme $dir/launcher.rasi
}

rofi_cmd
